# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjjIVi6T2hHTcNWGXS7OeFe-FLMfz5sD
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px  # Added for better visuals
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, 
    confusion_matrix, matthews_corrcoef, roc_auc_score, 
    classification_report
)

# 1. Page Configuration
st.set_page_config(page_title="Mobile Price Analytics", layout="wide", initial_sidebar_state="expanded")

# Custom CSS for a modern look
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

st.title("📱 Mobile Price Classification Intelligence")
st.markdown("---")

# 2. Sidebar with enhanced info
st.sidebar.header("🕹️ Control Panel")
model_name = st.sidebar.selectbox("Select Model", ["Logistic Regression", "Decision Tree", "KNN", "Naive Bayes", "Random Forest", "XGBoost"])

@st.cache_resource
def load_model_resources(name):
    try:
        model = joblib.load(f"models/{name.replace(' ', '_').lower()}.pkl")
        scaler = joblib.load('models/scaler.pkl')
        return model, scaler
    except:
        return None, None

model, scaler = load_model_resources(model_name)

# Sidebar Download & Info
st.sidebar.markdown("---")
try:
    with open("test_data.csv", "rb") as f:
        st.sidebar.download_button("📥 Download Sample Data", f, "test_data.csv")
except:
    pass

st.sidebar.info(f"**Current Model:** {model_name}\n\nThis app predicts price range (0-3) based on hardware specs.")

# 3. Main Logic
uploaded_file = st.file_uploader("📂 Upload Mobile Dataset (CSV)", type=["csv"])

if uploaded_file is not None and model is not None:
    df = pd.read_csv(uploaded_file)
    
    # Preprocessing
    X = df.drop('price_range', axis=1) if 'price_range' in df.columns else df
    y_true = df['price_range'] if 'price_range' in df.columns else None

    # Prediction Logic
    X_input = scaler.transform(X) if model_name in ["Logistic Regression", "KNN"] else X
    y_pred = model.predict(X_input)
    y_prob = model.predict_proba(X_input)

    # --- SECTION 1: DASHBOARD ---
    st.subheader("🚀 Performance Dashboard")
    if y_true is not None:
        c1, c2, c3, c4, c5, c6 = st.columns(6)
        c1.metric("Accuracy", f"{accuracy_score(y_true, y_pred):.2%}")
        try:
            auc = roc_auc_score(y_true, y_prob, multi_class='ovr')
            c2.metric("AUC", f"{auc:.3f}")
        except:
            c2.metric("AUC", "N/A")
        c3.metric("Precision", f"{precision_score(y_true, y_pred, average='weighted'):.2f}")
        c4.metric("Recall", f"{recall_score(y_true, y_pred, average='weighted'):.2f}")
        c5.metric("F1 Score", f"{f1_score(y_true, y_pred, average='weighted'):.2f}")
        c6.metric("MCC", f"{matthews_corrcoef(y_true, y_pred):.2f}")

    # --- SECTION 2: TABS ---
    st.markdown("---")
    tab1, tab2, tab3 = st.tabs(["🔍 Confusion Analysis", "📋 Report Details", "📈 Prediction Distribution"])

    with tab1:
        st.write("#### Confusion Matrix Interpretation")
        col_cm1, col_cm2 = st.columns([2, 1])
        with col_cm1:
            fig, ax = plt.subplots(figsize=(8, 4))
            sns.heatmap(confusion_matrix(y_true, y_pred), annot=True, fmt='d', cmap='Blues')
            plt.xlabel('Predicted Label')
            plt.ylabel('True Label')
            st.pyplot(fig)
        with col_cm2:
            st.write("**Quick Guide:**")
            st.caption("Diagonal elements represent correct predictions.")
            st.caption("Off-diagonal elements show where the model is confusing classes.")

    with tab2:
        st.write("#### Detailed Classification Metrics")
        report_dict = classification_report(y_true, y_pred, output_dict=True)
        report_df = pd.DataFrame(report_dict).transpose()
        st.dataframe(report_df.style.background_gradient(cmap='RdYlGn').format("{:.2f}"), use_container_width=True)

    with tab3:
        st.write("#### Forecast Distribution")
        res_summary = pd.DataFrame({'Class': y_pred}).value_counts().reset_index()
        res_summary.columns = ['Price Range', 'Count']
        fig_pie = px.pie(res_summary, values='Count', names='Price Range', hole=0.4, 
                         color_discrete_sequence=px.colors.sequential.RdBu)
        st.plotly_chart(fig_pie, use_container_width=True)

    # --- SECTION 3: DATA INSIGHTS ---
    st.markdown("---")
    st.subheader("📋 Prediction Insights")
    
    # Filter functionality for better UI
    col_f1, col_f2 = st.columns(2)
    with col_f1:
        search_val = st.multiselect("Filter by Predicted Price Range", options=[0,1,2,3], default=[0,1,2,3])
    
    res_df = df.copy()
    res_df.insert(0, 'Predicted_Range', y_pred)
    filtered_df = res_df[res_df['Predicted_Range'].isin(search_val)]
    
    st.dataframe(filtered_df, use_container_width=True)

elif model is None:
    st.error("Model files missing. Please check the 'models/' folder.")
