# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjjIVi6T2hHTcNWGXS7OeFe-FLMfz5sD
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, matthews_corrcoef, roc_auc_score

# ==========================================
# 1. Page Configuration
# ==========================================
st.set_page_config(
    page_title="Mobile Price Classification",
    page_icon="📱",
    layout="wide"
)

# Title and Sub-header
st.title("📱 Mobile Price Classification System")
st.markdown("### BITS Pilani M.Tech Assignment 2 | Machine Learning Deployment")
st.markdown("---")

# ==========================================
# 2. Sidebar: Configuration
# ==========================================
st.sidebar.header("⚙️ Configuration")

# Model Selection
model_name = st.sidebar.selectbox(
    "Select Model",
    ["Logistic Regression", "Decision Tree", "KNN", "Naive Bayes", "Random Forest", "XGBoost"]
)

# Load Resources
@st.cache_resource
def load_resources(name):
    try:
        scaler = joblib.load('models/scaler.pkl')
        model = joblib.load(f"models/{name.replace(' ', '_').lower()}.pkl")
        return model, scaler
    except:
        return None, None

model, scaler = load_resources(model_name)

if model is None:
    st.error("❌ Error: Models not found. Please upload the 'models' folder to GitHub.")
    st.stop()

# Download Button Logic
st.sidebar.markdown("---")
st.sidebar.info("Tip: Download sample data to test the app.")
try:
    with open("test_data.csv", "rb") as file:
        st.sidebar.download_button(
            label="📥 Download Test Data",
            data=file,
            file_name="test_data.csv",
            mime="text/csv"
        )
except FileNotFoundError:
    st.sidebar.warning("⚠️ test_data.csv not found.")

# ==========================================
# 3. Main Interface
# ==========================================
uploaded_file = st.file_uploader("📂 Upload your CSV file here", type=["csv"])

if uploaded_file is not None:
    # Read Data
    df = pd.read_csv(uploaded_file)

    # Preprocessing
    if 'price_range' in df.columns:
        X_test = df.drop('price_range', axis=1)
        y_true = df['price_range']
    else:
        X_test = df
        y_true = None

    # Scale if needed
    if model_name in ["Logistic Regression", "KNN"]:
        X_test_scaled = scaler.transform(X_test)
    else:
        X_test_scaled = X_test

    # Predict
    y_pred = model.predict(X_test_scaled)
    y_prob = model.predict_proba(X_test_scaled)

    # --- RESULTS SECTION ---
    st.success(f"✅ Prediction Complete using {model_name}")

    if y_true is not None:
        # 1. Metrics Dashboard
        st.subheader("📊 Performance Metrics")

        # Calculate Metrics
        acc = accuracy_score(y_true, y_pred)
        auc = roc_auc_score(y_true, y_prob, multi_class='ovr')
        prec = precision_score(y_true, y_pred, average='weighted')
        rec = recall_score(y_true, y_pred, average='weighted')
        f1 = f1_score(y_true, y_pred, average='weighted')
        mcc = matthews_corrcoef(y_true, y_pred)

        # Row 1
        col1, col2, col3 = st.columns(3)
        col1.metric("Accuracy", f"{acc:.2%}", delta_color="normal")
        col2.metric("AUC Score", f"{auc:.3f}")
        col3.metric("MCC Score", f"{mcc:.3f}")

        # Row 2
        col4, col5, col6 = st.columns(3)
        col4.metric("Precision", f"{prec:.3f}")
        col5.metric("Recall", f"{rec:.3f}")
        col6.metric("F1 Score", f"{f1:.3f}")

        st.markdown("---")

        # 2. Visualizations (Confusion Matrix + Class Distribution)
        col_viz1, col_viz2 = st.columns(2)

        with col_viz1:
            st.subheader("Confusion Matrix")
            cm = confusion_matrix(y_true, y_pred)
            fig, ax = plt.subplots()
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
            plt.ylabel('Actual Class')
            plt.xlabel('Predicted Class')
            st.pyplot(fig)

        with col_viz2:
            st.subheader("Prediction Distribution")
            # Create a simple bar chart of predicted classes
            pred_counts = pd.Series(y_pred).value_counts().sort_index()
            st.bar_chart(pred_counts)
            st.caption("Count of phones predicted in each price range (0-3).")

    # 3. Data Table
    st.markdown("---")
    st.subheader("📋 Detailed Prediction Data")

    results_df = df.copy()
    results_df['Predicted_Price_Range'] = y_pred

    # Highlight the predicted column by moving it to the front
    cols = ['Predicted_Price_Range'] + [col for col in results_df.columns if col != 'Predicted_Price_Range']
    results_df = results_df[cols]

    st.dataframe(results_df, use_container_width=True)

elif uploaded_file is None:
    st.info("👈 Please upload a CSV file to generate predictions.")